### ISSUE TITLE
Q2 Dependabot application dependency updates

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#172]
### Benefit Hypothesis

UGRC applications have dependencies that are constantly updating to add new features, improve performance, and patch security issues. Keeping applications current with dependencies improves our security posture and allows for easier future enhancements since the amount of breaking changes is smaller and more trivial.

### Acceptance Criteria

UGRC application dependencies are current and all known CVE's are patched.

**Comment by nathankota** [comment]
### Sprint # Tasks
- [ ] Investigate and implement some [Dependabot groups](https://github.blog/2023-08-24-a-faster-way-to-manage-version-updates-with-dependabot/) 
- [ ] Dependabot updates

**Comment by steveoh** [comment]
## Sprint 1 Notes

Scott and Steve have completed 99% of this quarters dependabot updates. Below are some notes that we have to close out the task and some we want to push to the next quarter.

### Remaining tasks

- [ ] API Client build needs to be investigated
- [ ] Parole needs code changes
- [ ] Address point editor needs updates but we aren’t sure where to invest time
- [ ] Jake hasn't started his python projects
- [ ] Revisit the reactfire npm conflicts
- [ ] Some action workflows are not completing since their required checks aren’t running

### Next quarter

1. Forklift arcpy + warehouse updates we'd like to push for next quarter

**Comment by nathankota** [comment]
will move unchecked tasks and new ones to a Q3 feature
