### ISSUE TITLE
Lt. Gov Elections - ETL for VISTA replacement

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#359]
### Benefit

The Lt. Gov's Election Office is working with a company (BPro Inc) to build a new system (TotalVote) to replace VISTA. The system requires some data sets (addresses, boundaries of precincts, cities, zip, counties) in particular schemas and formats. Lt Gov's Office requests UGRC's assistance in writing scripts to ETL data from our data services to the required schema and format for the TotalVote system. 

### Acceptance Criteria

- [x] Review [TotalVote documentation](https://drive.google.com/drive/folders/1zDVUfsEw0K1Z0TXwQJ5SR1ih9_E4-EMo), meet and work as a team to determine best solution
- [x] Build scripts/process to ETL UGRC data to TotalVote schema
- [x] Scripts are stored in the UGRC github repository and peer-reviewed
- **Explore:** Enable replication of the ETL process by TotalVote or Lt Gov Elections for future ETL needs?

### Risks

- Inability to fulfill the schema requirements of the TotalVote system with existing UGRC data
- Inability to simplify the use of the scripts to hand over to vendor and/or Lt. Gov Elections
- Lack of ownership by the vendor and/or Lt Gov Elections to run the script themselves in the future
- Client's scope and expectation changes

### Issue Reference

refs #

**Comment by nathankota** [comment]
### Sprint 1
- Review documentation
- Meet and discuss a plan

**Comment by nathankota** [comment]
### Sprint 2
- [ ] Meet with Lt. Gov Elections and vendor about the questions/comments above

**Comment by nathankota** [comment]
### Sprint 4
Build scripts according to [specs](https://drive.google.com/drive/folders/1zDVUfsEw0K1Z0TXwQJ5SR1ih9_E4-EMo) for:

- TotalAddress Foundational Map Layers
  - [ ] Precinct Part (UGRC: [Utah Vista Ballot Areas](https://opendata.gis.utah.gov/datasets/utah-vista-ballot-areas/explore))
  - [ ] City (UGRC: [Utah Municipal Boundaries](https://opendata.gis.utah.gov/datasets/utah-municipal-boundaries/explore))
  - [ ] Zip Code (UGRC: [Utah Zip Code Areas](https://opendata.gis.utah.gov/datasets/utah-zip-code-areas/explore))
  - [ ] Statewide County Boundary (UGRC: [Utah County Boundaries](https://opendata.gis.utah.gov/datasets/utah-county-boundaries/explore))

- [ ] TotalAddress Address Import (UGRC: [Utah Address Points](https://opendata.gis.utah.gov/datasets/utah-address-points/explore))

**Comment by ZachBeck** [comment]
Script loaded into github and reviewed by Jake on 06/05/2024

**Comment by steveoh** [comment]
> * Script loaded into github

Do you have a link?

**Comment by ZachBeck** [comment]
https://github.com/ZachBeck/total-address-etl

**Comment by ZachBeck** [comment]
Precincts json with updated precinct ids sent for review.

**Comment by ZachBeck** [comment]
waiting to hear back about data sent for review

**Comment by nathankota** [comment]
Carried-forward to FY25 Q1

**Comment by ZachBeck** [comment]
###FY25 Sprint 2 NOTES
Emailed response to Total Address feedback:

Hi Ali,
I'm slowly working through the list of errors. Here is what I have so far from your previously attached corrections doc.

Invalid Zip Codes:
There are some sliver areas where an address is being assigned an incorrect zip that I'll be able to fix in the coming weeks. However, there are large pockets of addresses that I think are being flagged as errors incorrectly. All the flagged addresses that I checked with the USPS in the Hooper, Ballard, and Woodland areas have the correct zip. 5865 W 5500 S, Hooper, 84315, for example was flagged. Let me know what is causing the error and I can get it fixed.

Invalid Street Names:
These should be fixed now and an updated dataset can be found at:
https://drive.google.com/file/d/18aEvLa1PYySaOBMJaKGn0-yNZSVRoY4K/view?usp=sharing

Original address does not equal the final:
I'll have this fixed in the coming weeks. I didn't realize this field needed the address with the city and zip included (1595 E HIGHLAND TRAILS RD ENOCH 84721) where I was leaving that off (1595 E HIGHLAND TRAILS RD).

I'll keep you posted on my progress. In the future, how often would you like to have address updates?

**Comment by steveoh** [comment]
> Requirement: The scripts must be reviewed by another team member and live in the UGRC GitHub repository

> [ZachBeck/total-address-etl](https://github.com/ZachBeck/total-address-etl)

Nathan's request was to load the code into the agrc org's github. In the repo settings you can request to transfer it.

**Comment by ZachBeck** [comment]
Jake has already reviewed them.

**Comment by nathankota** [comment]
https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

> To transfer a repository that you own to an organization, you must have permission to create a repository in the target organization.

@ZachBeck do you have permissions to create a repo in the agrc org and, if not, @steveoh can he be granted permission temporarily to make the transfer?

**Comment by ZachBeck** [comment]
It looks like I have permissions.
